(require 'init-straight)
(require 'init-evil)
(require 'init-completion)
(require 'init-minibuffer)
(require 'init-magit)
(require 'init-undo-tree)
(require 'init-ace-window)
(require 'init-which-key)
(require 'init-format)
;; (require 'init-awesome-tray)
(require 'init-tree-sitter)
;; (require 'init-rainbow-delimiters)

(provide 'init-packages)
