(require 'init-straight)
(require 'init-evil)
(require 'init-lsp-bridge)
(require 'init-minibuffer)
(require 'init-magit)
(require 'init-undo-tree)
(require 'init-ace-window)
(require 'init-tree-sitter)
(require 'init-which-key)

(provide 'init-packages)
