(require 'init-theme)
(require 'init-evil)
(require 'init-gcmh)
(require 'init-minibuffer)
(require 'init-completion)
(require 'init-ace-window)
(require 'init-formatter)
(require 'init-indent-line)
;; (require 'init-tree-sitter)
(require 'init-undo-tree)
(require 'init-git)
(require 'init-org)
(require 'init-which-key)
;; (require 'init-rainbow-delimiters)
;; (require 'init-awesome-tray)
(require 'init-keybindings)
(require 'init-sort-tab)
;; (require 'init-holo-layer)
(require 'init-awesome-tray)
(require 'init-dashboard)

(provide 'init-packages)
